image: node:18

variables:
  GCP_PROJECT_ID: "zena-harris-works"
  REGION: "us-west1"

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm test

build:
  stage: build
  script:
    - npm run build
    - docker build -t gcr.io/$GCP_PROJECT_ID/zena-app .
    - docker push gcr.io/$GCP_PROJECT_ID/zena-app

deploy:
  stage: deploy
  script:
    - echo $GCP_SA_KEY > /tmp/gcp-key.json
    - gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
    - gcloud run deploy zena-service \
      --image gcr.io/$GCP_PROJECT_ID/zena-app \
      --platform managed \
      --region $REGION \
      --allow-unauthenticated